development: &development
  adapter: mysql2
  database: buildingsync_dashboard_development
  host: localhost

docker-development: &docker-development
  adapter: mysql2
  database: buildingsync_dashboard_development
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db
  port: 3306

test:
  <<: *development
  database: projectmonitor_test

production:
  <<: *development
  database: projectmonitor_production
